using System.ComponentModel;
using System.Text.Json.Serialization;

namespace Identity.Domain.Enums
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum Wards
    {
        [Description("Phường Thủ Dầu Một")] PhuongThuDauMot,
        [Description("Phường Phú Lợi")] PhuongPhuLoi,
        [Description("Phường Bình Dương")] PhuongBinhDuong,
        [Description("Phường Phú An")] PhuongPhuAn,
        [Description("Phường Chánh Hiệp")] PhuongChanhHiep,
        [Description("Xã Dầu Tiếng")] XaDauTieng,
        [Description("Xã Minh Thạnh")] XaMinhThanh,
        [Description("Xã Long Hòa")] XaLongHoa,
        [Description("Xã Thanh An")] XaThanhAn,
        [Description("Phường Bến Cát")] PhuongBenCat,
        [Description("Xã Trừ Văn Thố")] XaTruVanTho,
        [Description("Xã Bàu Bàng")] XaBauBang,
        [Description("Phường Chánh Phú Hòa")] PhuongChanhPhuHoa,
        [Description("Phường Long Nguyên")] PhuongLongNguyen,
        [Description("Phường Tây Nam")] PhuongTayNam,
        [Description("Phường Thới Hòa")] PhuongThoiHoa,
        [Description("Phường Hòa Lợi")] PhuongHoaLoi,
        [Description("Xã Phú Giáo")] XaPhuGiao,
        [Description("Xã Phước Thành")] XaPhuocThanh,
        [Description("Xã An Long")] XaAnLong,
        [Description("Xã Phước Hòa")] XaPhuocHoa,
        [Description("Phường Tân Uyên")] PhuongTanUyen,
        [Description("Phường Tân Khánh")] PhuongTanKhanh,
        [Description("Xã Bắc Tân Uyên")] XaBacTanUyen,
        [Description("Xã Thường Tân")] XaThuongTan,
        [Description("Phường Vĩnh Tân")] PhuongVinhTan,
        [Description("Phường Bình Cơ")] PhuongBinhCo,
        [Description("Phường Tân Hiệp")] PhuongTanHiep,
        [Description("Phường Dĩ An")] PhuongDiAn,
        [Description("Phường Tân Đông Hiệp")] PhuongTanDongHiep,
        [Description("Phường Đông Hòa")] PhuongDongHoa,
        [Description("Phường Lái Thiêu")] PhuongLaiThieu,
        [Description("Phường Thuận Giao")] PhuongThuanGiao,
        [Description("Phường An Phú")] PhuongAnPhu,
        [Description("Phường Thuận An")] PhuongThuanAn,
        [Description("Phường Bình Hòa")] PhuongBinhHoa,
        [Description("Phường Vũng Tàu")] PhuongVungTau,
        [Description("Phường Tam Thắng")] PhuongTamThang,
        [Description("Phường Rạch Dừa")] PhuongRachDua,
        [Description("Phường Phước Thắng")] PhuongPhuocThang,
        [Description("Xã Long Sơn")] XaLongSon,
        [Description("Phường Bà Rịa")] PhuongBaRia,
        [Description("Phường Long Hương")] PhuongLongHuong,
        [Description("Phường Tam Long")] PhuongTamLong,
        [Description("Xã Ngãi Giao")] XaNgaiGiao,
        [Description("Xã Xuân Sơn")] XaXuanSon,
        [Description("Xã Bình Giã")] XaBinhGia,
        [Description("Xã Châu Đức")] XaChauDuc,
        [Description("Xã Kim Long")] XaKimLong,
        [Description("Xã Nghĩa Thành")] XaNgiaThanh,
        [Description("Xã Hồ Tràm")] XaHoTram,
        [Description("Xã Xuyên Mộc")] XaXuyenMoc,
        [Description("Xã Bàu Lâm")] XaBauLam,
        [Description("Xã Hòa Hội")] XaHoaHoi,
        [Description("Xã Hòa Hiệp")] XaHoaHiep,
        [Description("Xã Bình Châu")] XaBinhChau,
        [Description("Xã Long Điền")] XaLongDien,
        [Description("Xã Long Hải")] XaLongHai,
        [Description("Xã Đất Đỏ")] XaDatDo,
        [Description("Xã Phước Hải")] XaPhuocHai,
        [Description("Phường Phú Mỹ")] PhuongPhuMy,
        [Description("Phường Tân Hải")] PhuongTanHai,
        [Description("Phường Tân Phước")] PhuongTanPhuoc,
        [Description("Phường Tân Thành")] PhuongTanThanh,
        [Description("Xã Châu Pha")] XaChauPha,
        [Description("Đặc khu Côn Đảo")] DacKhuConDao,
        [Description("Phường Tân Định")] PhuongTanDinh,
        [Description("Phường Sài Gòn")] PhuongSaiGon,
        [Description("Phường Bến Thành")] PhuongBenThanh,
        [Description("Phường Cầu Ông Lãnh")] PhuongCauOngLanh,
        [Description("Phường An Phú Đông")] PhuongAnPhuDong,
        [Description("Phường Thới An")] PhuongThoiAn,
        [Description("Phường Tân Thới Hiệp")] PhuongTanThoiHiep,
        [Description("Phường Trung Mỹ Tây")] PhuongTrungMyTay,
        [Description("Phường Đông Hưng Thuận")] PhuongDongHungThuan,
        [Description("Phường Linh Xuân")] PhuongLinhXuan,
        [Description("Phường Tam Bình")] PhuongTamBinh,
        [Description("Phường Hiệp Bình")] PhuongHiepBinh,
        [Description("Phường Thủ Đức")] PhuongThuDuc,
        [Description("Phường Long Bình")] PhuongLongBinh,
        [Description("Phường Tăng Nhơn Phú")] PhuongTangNhonPhu,
        [Description("Phường Phước Long")] PhuongPhuocLong,
        [Description("Phường Long Phước")] PhuongLongPhuoc,
        [Description("Phường Long Trường")] PhuongLongTruong,
        [Description("Phường An Nhơn")] PhuongAnNhon,
        [Description("Phường An Hội Đông")] PhuongAnHoiDong,
        [Description("Phường An Hội Tây")] PhuongAnHoiTay,
        [Description("Phường Gò Vấp")] PhuongGoVap,
        [Description("Phường Hạnh Thông")] PhuongHanhThong,
        [Description("Phường Thông Tây Hội")] PhuongThongTayHoi,
        [Description("Phường Bình Lợi Trung")] PhuongBinhLoiTrung,
        [Description("Phường Bình Quới")] PhuongBinhQui,
        [Description("Phường Bình Thạnh")] PhuongBinhThanh,
        [Description("Phường Gia Định")] PhuongGiaDinh,
        [Description("Phường Thạnh Mỹ Tây")] PhuongThanhMyTay,
        [Description("Phường Tân Sơn Nhất")] PhuongTanSonNhat,
        [Description("Phường Tân Sơn Hòa")] PhuongTanSonHoa,
        [Description("Phường Bảy Hiền")] PhuongBayHien,
        [Description("Phường Tân Hòa")] PhuongTanHoa,
        [Description("Phường Tân Bình")] PhuongTanBinh,
        [Description("Phường Tân Sơn")] PhuongTanSon,
        [Description("Phường Tây Thạnh")] PhuongTayThanh,
        [Description("Phường Tân Sơn Nhì")] PhuongTanSonNhi,
        [Description("Phường Phú Thọ Hòa")] PhuongPhuThoHoa,
        [Description("Phường Phú Thạnh")] PhuongPhuThanh,
        [Description("Phường Tân Phú")] PhuongTanPhu,
        [Description("Phường Đức Nhuận")] PhuongDucNhuan,
        [Description("Phường Cầu Kiệu")] PhuongCauKieu,
        [Description("Phường Phú Nhuận")] PhuongPhuNhuan,
        [Description("Phường An Khánh")] PhuongAnKhanh,
        [Description("Phường Bình Trưng")] PhuongBinhTrung,
        [Description("Phường Cát Lái")] PhuongCatLai,
        [Description("Phường Xuân Hòa")] PhuongXuanHoa,
        [Description("Phường Nhiêu Lộc")] PhuongNhieuLoc,
        [Description("Phường Bàn Cờ")] PhuongBanCo,
        [Description("Phường Hòa Hưng")] PhuongHoaHung,
        [Description("Phường Diên Hồng")] PhuongDienHong,
        [Description("Phường Vườn Lài")] PhuongVuonLai,
        [Description("Phường Hòa Bình")] PhuongHoaBinh,
        [Description("Phường Phú Thọ")] PhuongPhuTho,
        [Description("Phường Bình Thới")] PhuongBinhThoi,
        [Description("Phường Minh Phụng")] PhuongMinhPhung,
        [Description("Phường Xóm Chiếu")] PhuongXomChieu,
        [Description("Phường Khánh Hội")] PhuongKhanhHoi,
        [Description("Phường Vĩnh Hội")] PhuongVinhHoi,
        [Description("Phường Chợ Quán")] PhuongChoQuan,
        [Description("Phường An Đông")] PhuongAnDong,
        [Description("Phường Chợ Lớn")] PhuongChoLon,
        [Description("Phường Phú Lâm")] PhuongPhuLam,
        [Description("Phường Bình Phú")] PhuongBinhPhu,
        [Description("Phường Bình Tây")] PhuongBinhTay,
        [Description("Phường Bình Tiên")] PhuongBinhTien,
        [Description("Phường Chánh Hưng")] PhuongChanhHung,
        [Description("Phường Bình Đông")] PhuongBinhDong,
        [Description("Phường Phú Định")] PhuongPhuDinh,
        [Description("Phường Bình Hưng Hòa")] PhuongBinhHungHoa,
        [Description("Phường Bình Tân")] PhuongBinhTan,
        [Description("Phường Bình Trị Đông")] PhuongBinhTriDong,
        [Description("Phường Tân Tạo")] PhuongTanTao,
        [Description("Phường An Lạc")] PhuongAnLac,
        [Description("Phường Tân Hưng")] PhuongTanHung,
        [Description("Phường Tân Thuận")] PhuongTanThuan,
        [Description("Phường Phú Thuận")] PhuongPhuThuan,
        [Description("Phường Tân Mỹ")] PhuongTanMy,
        [Description("Xã Tân An Hội")] XaTanAnHoi,
        [Description("Xã An Nhơn Tây")] XaAnNhonTay,
        [Description("Xã Nhuận Đức")] XaNhuanDuc,
        [Description("Xã Thái Mỹ")] XaThaiMy,
        [Description("Xã Phú Hòa Đông")] XaPhuHoaDong,
        [Description("Xã Bình Mỹ")] XaBinhMy,
        [Description("Xã Củ Chi")] XaCuChi,
        [Description("Xã Hóc Môn")] XaHocMon,
        [Description("Xã Đông Thạnh")] XaDongThanh,
        [Description("Xã Xuân Thới Sơn")] XaXuanThoiSon,
        [Description("Xã Bà Điểm")] XaBaDiem,
        [Description("Xã Tân Nhựt")] XaTanNhut,
        [Description("Xã Vĩnh Lộc")] XaVinhLoc,
        [Description("Xã Tân Vĩnh Lộc")] XaTanVinhLoc,
        [Description("Xã Bình Lợi")] XaBinhLoi,
        [Description("Xã Bình Hưng")] XaBinhHung,
        [Description("Xã Hưng Long")] XaHungLong,
        [Description("Xã Bình Chánh")] XaBinhChanh,
        [Description("Xã Nhà Bè")] XaNhaBe,
        [Description("Xã Hiệp Phước")] XaHiepPhuoc,
        [Description("Xã Cần Giờ")] XaCanGio,
        [Description("Xã Bình Khánh")] XaBinhKhanh,
        [Description("Xã An Thới Đông")] XaAnThoiDong,
        [Description("Xã Thạnh An")] XaThanhjAn
    }
}
